# Generated by Django 2.2.1 on 2019-06-04 06:02

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import quotium.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('property_address', models.CharField(max_length=300)),
                ('zip_code', models.CharField(max_length=5, validators=[quotium.models.validate_zipcode])),
                ('number_bedrooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('number_bathrooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('square_footage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)])),
            ],
        ),
        migrations.CreateModel(
            name='QuoteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 4, 6, 2, 15, 218605, tzinfo=utc))),
                ('monthly_estimate', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100000000)])),
                ('property_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotium.PropertyData')),
            ],
        ),
    ]
