# Generated by Django 2.2.1 on 2019-06-04 06:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quotium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterecord',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 4, 6, 2, 35, 708351, tzinfo=utc)),
        ),
    ]
