# Generated by Django 2.2.1 on 2019-06-04 22:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quotium', '0002_auto_20190604_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterecord',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 4, 22, 27, 4, 71397, tzinfo=utc)),
        ),
    ]
