# Generated by Django 2.2.1 on 2019-06-04 23:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotium', '0003_auto_20190604_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
