# Generated by Django 2.2.1 on 2019-06-07 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotium', '0004_auto_20190604_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydata',
            name='number_bathrooms',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)]),
        ),
        migrations.AlterField(
            model_name='propertydata',
            name='number_bedrooms',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
